# Generated by Django 2.2.7 on 2020-10-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('kakaoemail', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('continuemonth', models.IntegerField()),
            ],
        ),
    ]
