# Generated by Django 2.2.7 on 2020-10-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_payday',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='continuemonth',
            field=models.IntegerField(default=1),
        ),
    ]
