# Generated by Django 2.2.7 on 2020-10-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('kakaoemail', models.CharField(max_length=50)),
                ('liquornumber', models.IntegerField()),
                ('liquorname', models.CharField(max_length=100)),
                ('liquorprice', models.IntegerField(default=1)),
                ('quantity', models.IntegerField()),
                ('url', models.CharField(default='https://www.daelim.ac.kr/coming_soon.jpg', max_length=3000)),
            ],
        ),
    ]
