from django.db import models

# Create your models here.

class cforder(models.Model):
    class Meta:
        pass
    
    
    # user가 liquor에 해당하는 술을 샀는지?
    kakaoemail = models.CharField(max_length=100, null=False)
    liquor1 = models.FloatField(null=False)
    liquor2 = models.FloatField(null=False)
    liquor3= models.FloatField(null=False)
    liquor4= models.FloatField(null=False)
    liquor5= models.FloatField(null=False)
    liquor6= models.FloatField(null=False)
    liquor7= models.FloatField(null=False)
    liquor8= models.FloatField(null=False)
    liquor9= models.FloatField(null=False)
    liquor10= models.FloatField(null=False)
    liquor11= models.FloatField(null=False)
    liquor12= models.FloatField(null=False)
    liquor13= models.FloatField(null=False)
    liquor14= models.FloatField(null=False)
    liquor15= models.FloatField(null=False)
    liquor16= models.FloatField(null=False)
    liquor17= models.FloatField(null=False)
    liquor18= models.FloatField(null=False)
    liquor19= models.FloatField(null=False)
    liquor20= models.FloatField(null=False)
    liquor21= models.FloatField(null=False)
    liquor22= models.FloatField(null=False)
    liquor23= models.FloatField(null=False)
    liquor24= models.FloatField(null=False)
    liquor25= models.FloatField(null=False)
    liquor26= models.FloatField(null=False)
    liquor27= models.FloatField(null=False)
    liquor28= models.FloatField(null=False)
    liquor29= models.FloatField(null=False)
    liquor30= models.FloatField(null=False)
    liquor31= models.FloatField(null=False)
    liquor32= models.FloatField(null=False)
    liquor33= models.FloatField(null=False)
    liquor34= models.FloatField(null=False)
    liquor35= models.FloatField(null=False)
    liquor36= models.FloatField(null=False)
    liquor37= models.FloatField(null=False)
    liquor38= models.FloatField(null=False)
    liquor39= models.FloatField(null=False)
    liquor40= models.FloatField(null=False)
    liquor41= models.FloatField(null=False)
    liquor42= models.FloatField(null=False)
    liquor43= models.FloatField(null=False)
    liquor44= models.FloatField(null=False)
    liquor45= models.FloatField(null=False)
    liquor46= models.FloatField(null=False)
    liquor47= models.FloatField(null=False)
    liquor48= models.FloatField(null=False)
    liquor49= models.FloatField(null=False)
    liquor50= models.FloatField(null=False)
    liquor51= models.FloatField(null=False)
    liquor52= models.FloatField(null=False)
    liquor53= models.FloatField(null=False)
    liquor54= models.FloatField(null=False)
    liquor55= models.FloatField(null=False)
    liquor56= models.FloatField(null=False)
    liquor57= models.FloatField(null=False)
    liquor58= models.FloatField(null=False)
    liquor59= models.FloatField(null=False)
    liquor60= models.FloatField(null=False)
    liquor61= models.FloatField(null=False)
    liquor62= models.FloatField(null=False)
    liquor63= models.FloatField(null=False)
    liquor64= models.FloatField(null=False)
    liquor65= models.FloatField(null=False)
    liquor66= models.FloatField(null=False)
    liquor67= models.FloatField(null=False)
    liquor68= models.FloatField(null=False)
    liquor69= models.FloatField(null=False)
    liquor70= models.FloatField(null=False)
    liquor71= models.FloatField(null=False)
    liquor72= models.FloatField(null=False)
    liquor73= models.FloatField(null=False)
    liquor74= models.FloatField(null=False)
    liquor75= models.FloatField(null=False)
    liquor76= models.FloatField(null=False)
    liquor77= models.FloatField(null=False)
    liquor78= models.FloatField(null=False)
    liquor79= models.FloatField(null=False)
    liquor80= models.FloatField(null=False)
    liquor81= models.FloatField(null=False)
    liquor82= models.FloatField(null=False)
    liquor83= models.FloatField(null=False)
    liquor84= models.FloatField(null=False)
    liquor85= models.FloatField(null=False)
    liquor86= models.FloatField(null=False)
    liquor87= models.FloatField(null=False)
    liquor88= models.FloatField(null=False)
    liquor89= models.FloatField(null=False)
    liquor90= models.FloatField(null=False)
    liquor91= models.FloatField(null=False)
    liquor92= models.FloatField(null=False)
    liquor93= models.FloatField(null=False)
    liquor94= models.FloatField(null=False)
    liquor95= models.FloatField(null=False)
    liquor96= models.FloatField(null=False)
    liquor97= models.FloatField(null=False)
    liquor98= models.FloatField(null=False)
    liquor99= models.FloatField(null=False)
    liquor100=models.FloatField(null=False)
    liquor101=models.FloatField(null=False)
    liquor102=models.FloatField(null=False)
    liquor103=models.FloatField(null=False)
    liquor104=models.FloatField(null=False)
    liquor105=models.FloatField(null=False)
    liquor106=models.FloatField(null=False)
    liquor107=models.FloatField(null=False)
    liquor108=models.FloatField(null=False)
    liquor109=models.FloatField(null=False)
    liquor110=models.FloatField(null=False)
    liquor111=models.FloatField(null=False)
    liquor112=models.FloatField(null=False)
    liquor113=models.FloatField(null=False)
    liquor114=models.FloatField(null=False)
    liquor115=models.FloatField(null=False)
    liquor116=models.FloatField(null=False)
    liquor117=models.FloatField(null=False)
    liquor118=models.FloatField(null=False)
    liquor119=models.FloatField(null=False)
    liquor120=models.FloatField(null=False)

    