# Generated by Django 2.2.7 on 2020-10-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liquor',
            fields=[
                ('liquornumber', models.AutoField(primary_key=True, serialize=False)),
                ('liquorname', models.CharField(max_length=50)),
                ('liquorarea', models.CharField(max_length=50)),
                ('liquorcategory', models.CharField(max_length=50)),
                ('liquoralcohol', models.CharField(max_length=10)),
                ('liquorprice', models.IntegerField()),
                ('liquoringredient', models.CharField(default='', max_length=1000, null=True)),
                ('sweet', models.IntegerField(default=0)),
                ('sour', models.IntegerField(default=0)),
                ('cloudy', models.IntegerField(default=0)),
                ('carbonated', models.IntegerField(default=0)),
                ('plain', models.IntegerField(default=0)),
                ('body', models.IntegerField(default=0)),
                ('bitter', models.IntegerField(default=0)),
                ('fancy', models.IntegerField(default=0)),
                ('spicy', models.IntegerField(default=0)),
                ('salty', models.IntegerField(default=0)),
                ('sourness', models.IntegerField(default=0)),
                ('acerbity', models.IntegerField(default=0)),
                ('flavor', models.IntegerField(default=0)),
                ('url', models.CharField(default='https://www.daelim.ac.kr/coming_soon.jpg', max_length=3000)),
            ],
        ),
    ]
